Fix payload parsing for subscriptions
Urigo/SOFA pull request #1148
Opened 2022-08-18 13:12 UTC by csuriano23

Currently the subscription manager do not parse in a proper way the JSON payload for parametrical subscriptions.

This PR fixes this behaviour, applying in the existing reduction the event variables to the subscription schema and using for each variable the designated name from the schema

2022-08-22 09:13 UTC, ardatan commented
Hi @csuriano23 !
Thanks for the PR!
Do you think we can add some tests to prevent future regressions?

2022-08-22 09:13 UTC, ardatan requested changes
Do you think we can add some tests to prevent future regressions?

2022-08-22 11:11 UTC, csuriano23 commented
Sure, I have to give a look on how the tests are structured and I am adding a case

2022-08-23 07:08 UTC, csuriano23 commented
@ardatan Done. Take a look

2022-09-21 13:19 UTC, merged

2022-09-21 14:36 UTC, ardatan commented
Thank you @csuriano23 !