New Website: Sofa
Urigo/SOFA pull request #1162
Opened 2022-09-15 14:19 UTC by TuvalSimha

2022-09-19 06:22 UTC, dotansimha commented
regarding tokens: in this repo, only @Urigo can add

2022-09-19 07:42 UTC, Urigo commented
Added them all yesterday

2022-09-22 05:29 UTC, dotansimha approved these changes

2022-09-22 05:29 UTC, dotansimha commented
@TuvalSimha looks good. feel free to merge and continue with the process.

2022-09-22 05:50 UTC, ardatan requested changes
How about the animation?

2022-09-22 06:24 UTC, ardatan commented on website/public/sitemap.xml
> +<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:news="http://www.google.com/schemas/sitemap-news/0.9" xmlns:xhtml="http://www.w3.org/1999/xhtml" xmlns:mobile="http://www.google.com/
Should we git ignore this? @dotansimha

2022-09-22 06:24 UTC, ardatan commented on website/public/_redirects
> +/docs/introduction /docs 301
Also this?
@dotansimha

2022-09-22 07:35 UTC, B2o5T commented on .gitignore
> +next
what the purpose of this ignore?

2022-09-22 07:35 UTC, B2o5T commented on website/.eslintrc.cjs
> +};
you don't need eslint config in website

2022-09-22 07:36 UTC, B2o5T commented on website/README.md
> +If you are using GitHub pages for hosting, this command is a convenient way to build the website and push to the `gh-pages` branch.
from where you copied this readme? just remove it

2022-09-22 07:37 UTC, B2o5T commented on website/next.config.mjs
> +      '/docs/introduction': '/docs',
this redirect is from graphql-config

2022-09-22 07:37 UTC, B2o5T commented on website/package.json
> +    "build": "next build && next-sitemap --config next-sitemap.config.cjs ",
```suggestion
    "build": "next build && next-sitemap --config next-sitemap.config.cjs",
```

2022-09-22 07:37 UTC, B2o5T commented on website/package.json
> +    "next": "next",
```suggestion
    "dev": "next",
```

2022-09-22 07:38 UTC, B2o5T commented on website/scripts/algolia-ci.mjs
> +import {indexToAlgolia} from '@guild-docs/algolia';
```suggestion
import {indexToAlgolia} from '@theguild/algolia';
```

2022-09-22 07:38 UTC, B2o5T commented on website/scripts/algolia-ci.mjs
> +import {indexToAlgolia} from '@guild-docs/algolia';
and remove old package and instal new one

2022-09-22 07:39 UTC, B2o5T commented on website/src/pages/meta.json
> +    }
```suggestion
    "type": "page"
```

2022-09-22 09:31 UTC, TuvalSimha commented on website/public/sitemap.xml
> +<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:news="http://www.google.com/schemas/sitemap-news/0.9" xmlns:xhtml="http://www.w3.org/1999/xhtml" xmlns:mobile="http://www.google.com/
Oh yeah, i will delete it

2022-09-22 09:31 UTC, TuvalSimha commented on website/public/_redirects
> +/docs/introduction /docs 301
The same

2022-09-22 09:32 UTC, TuvalSimha commented on .gitignore
> +next
Deleted :)

2022-09-22 09:32 UTC, TuvalSimha commented on website/.eslintrc.cjs
> +};
Deleted :)

2022-09-22 09:43 UTC, B2o5T commented on website/theme.config.tsx
> +const SITE_NAME = 'GraphQL Modules';
sofa

2022-09-23 06:03 UTC, merged